// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCalculator.DatabaseConnections;

#nullable disable

namespace WebCalculator.Migrations
{
    [DbContext(typeof(HistoryDatabaseContext))]
    partial class HistoryDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("WebCalculator.Models.ExpressionModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Result")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Expressions");
                });
#pragma warning restore 612, 618
        }
    }
}
